package com.yxld.yxchuangxin.db.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yxld.yxchuangxin.db.green.SPInfo;
import com.yxld.yxchuangxin.db.green.UserInfo;

import com.yxld.yxchuangxin.db.green.SPInfoDao;
import com.yxld.yxchuangxin.db.green.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sPInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final SPInfoDao sPInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sPInfoDaoConfig = daoConfigMap.get(SPInfoDao.class).clone();
        sPInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        sPInfoDao = new SPInfoDao(sPInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(SPInfo.class, sPInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        sPInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public SPInfoDao getSPInfoDao() {
        return sPInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
